 services:
  db:
    image: postgres:latest
    container_name : my_db_phunet
    ports: 
      - "65432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    
    environment: 
      POSTGRES_USER: ${POSTGRES_USE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  app:
    image: prawee/strapi
    container_name: my_app_phunet
    ports:
     - "8080:1337"
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: false